config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  root "menus#index"
  resources :mains do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :subs do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :soops do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :menus do
    resources :mains, only:[:index]
    resources :subs, only:[:index]
    resources :soops, only:[:index]
    collection do
      get "menu_index"
    end
  end

  

end

app/models/main.rb
class Main < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :menus
  belongs_to :user
  has_many :resipi_images, dependent: :destroy
  accepts_nested_attributes_for :resipi_images, allow_destroy: true
  belongs_to_active_hash :genre
  belongs_to_active_hash :type

  validates :main_name,              presence: true, uniqueness: { scope: :user_id}
  validates :genre_id,               presence: true
  validates :type_id,                presence: true
  
    def first_image
      resipi_images.first
    end
    
    scope :search, -> (search){where('main_name LIKE(?)', "%#{search}%")}
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only:[:show,:destroy,:edit,:update]
  def index
    @mains = Main.includes(:resipi_images)
  end

  def new
    if user_signed_in?
    @main = Main.new
    @main.resipi_images.new
    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def show
    if user_signed_in?
      @main_images = @main.resipi_images
    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def create
    @main = Main.new(mains_params)
    if user_signed_in?
      @main.user_id = current_user.id
      if @main.type_id.blank? == true || @main.genre_id.blank? == true
        redirect_to "/"
        flash[:alert] = '料理の種類かカテゴリーを選択し再度登録してください。'
      else
        if @main.save
          redirect_to "/"
          flash[:notice] = '登録が完了しました'
        else
          @main.resipi_images.new
          redirect_to "/"
          flash[:alert] = '料理がすでに登録されているか、空欄のため登録ができませんでした。'
        end
      end
    else
      redirect_to "/"
      flash[:alert] = '料理の登録にはログインが必要です。'
    end
  end

  def edit
    if user_signed_in?

    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def update
    if @main.update(main_update_params)
      flash[:notice] = '料理の編集が完了しました'
      redirect_to "/mains/menu_index"
    else
      flash[:alert] = '料理の編集に失敗しました'
      redirect_to "/"
    end
  end

  def destroy
    @main.destroy
    redirect_to root_path
    flash[:notice] = '料理が削除されました'
  end

  def menu_index
    if user_signed_in?
      @mains = Main.includes(:resipi_images).where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(5)
    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def search
    @mains = Main.search(params[:keyword]).where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(5)
  end

  def count
    @cnt = main.where(name: '検索結果').count
    render text: "検索結果は#(cnt)個です。"
  end


  private
  def mains_params
    params.require(:main).permit(:id,:main_name,:genre_id,:type_id,:comment,:user_id, resipi_images_attributes: [:image])
  end

  def main_update_params
    params.require(:main).permit(:id,:main_name,:genre_id,:type_id,:comment,:user_id,[resipi_images_attributes: [:image, :_destroy, :id]])
  end

  def set_main
    @main = Main.find(params[:id])
  end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/mains/edit.html.haml
.wrapper
  %h1.app-title Pochi
  .exhibit
    .exhibit__resipi
      .exhibit__resipi__resipiProfile
        .exhibit__resipi__resipiProfile__inputForm
        = form_with( model: @main, url: main_path, local: true) do |f|
          = render 'layouts/error_messages', model: f.object
          .exhibit__resipi__resipiProfile__inputForm__resipiImage
            .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__head
                .notation 料理画像
                .formRequire 必須
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__attention
                最大5枚までアップロードできます
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__box
                - if @main.persisted?
                  .prev-content
                    - @main.resipi_images.each_with_index do |image, i|
                      .preview-box
                        .upper-box
                          = image_tag image.image.url, data: { index: i }, width: "112", height: '112'
                        .lower-box
                          -# .update-box
                          -#   %label.edit-btn 編集
                          .delete-box
                            %span.js-remove 削除
                  .label-content
                    //プレビューの数に合わせてforオプションを指定
                    = f.label :"main-resipi_images_attributes_#{@main.resipi_images.length}_image", class: "label-box", id: "label-box--#{@main.resipi_images.length}" do
                      %pre.label-box__text-visible クリックしてファイルをアップロード
                      .hidden-content
                        = f.fields_for :resipi_images do |i|
                          //プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置
                          .js-file_group{"data-index" => "#{i.index}"}
                            = i.file_field :image, class: "hidden-field"
                          - if @main.persisted?
                            = i.check_box:_destroy, data:{ index: i.index },class: "hidden-checkbox"
                          - if @main.persisted?
                            .js-file_group{"data-index" => "#{@main.resipi_images.count}"}
                          - @main.resipi_images.length.upto(4) do |i|
                            %input{name: "main[resipi_images_attributes][#{i}][image]", id: "main_resipi_images_attributes_#{i}_image", class:"hidden-field", type:"file"}
                
                    
          = f.text_field :main_name, class: "exhibitInput", placeholder: "主菜を入力してください"
          = f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "カテゴリーを選択してください" }, class: "exhibitInput"
          = f.collection_select :type_id, Type.all, :id, :name, { prompt: "種類を選択してください" }, class: "exhibitInput"
          .submit-area
            = f.submit :料理を更新する ,class: "exhibitSubmit1"
            = link_to "/", data: {"turbolinks" => false},class: "exhibitSubmit2" do
              もどる
= render "layouts/footer"

app/views/mains/menu_index.html.haml
.wrapper
  %h1= link_to "Pochi", root_path,class: "app-title"
  .header__box__upper__search
    = form_with(url: search_mains_path, local: true, method: :get, class: "search-form") do |form|
      = form.text_field :keyword, placeholder: "キーワードから探す", class: "header__box__upper__search--input"
      %button{type: "submit", class: 'header__box__upper__search--btn'} 
        = icon('fas', 'search', class: 'search-icon')
  .week
    %h2.title 登録メニュー
    - @mains.each do |main|
      - if main.user_id == current_user.id
        .week__menu_show
          %td
            .pickup-container__product-box__product-lists__product-list
              = link_to main_path(main), data:{"turbolinks" => false}, class: "line" do
                - if main.first_image != nil
                  .content_post{:style => "background-image: url(#{main.first_image.image.url});"}
                - else
                  = ""
            .resipi_name
              = link_to "◎#{main.main_name}◎","/mains/#{main.id}"
      - else
        = ""
  .page
    = paginate(@mains)

  .submit_area            
    = link_to "今週のこんだてを決める", "/",data: {"turbolinks" => false},class: "exhibitSubmit1"
  = render "layouts/footer"

app/views/mains/new.html.haml
.wrapper
  %h1.app-title Pochi
  .exhibit
    .exhibit__resipi
      .exhibit__resipi__resipiProfile
        .exhibit__resipi__resipiProfile__inputForm
        = form_with( model: @main, url: mains_path, local: true) do |f|
          = render 'layouts/error_messages', model: f.object
          .exhibit__resipi__resipiProfile__inputForm__resipiImage
            .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__head
                .notation 出品画像
                .formRequire 必須
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__attention
                最大5枚までアップロードできます
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__box
                .prev-content
                .label-content
                  %label{for: "main_resipi_images_attributes_0_image", class: "label-box", id: "label-box--0"}
                    %pre.label-box__text-visible クリックしてファイルをアップロード
                .hidden-content
                  = f.fields_for :resipi_images do |i|
                    = i.file_field :image, class: "hidden-field"
                    %input{class:"hidden-field", type: "file", name: "main[resipi_images_attributes][1][image]", id: "main_resipi_images_attributes_1_image" }
                    %input{class:"hidden-field", type: "file", name: "main[resipi_images_attributes][2][image]", id: "main_resipi_images_attributes_2_image" }
                    %input{class:"hidden-field", type: "file", name: "main[resipi_images_attributes][3][image]", id: "main_resipi_images_attributes_3_image" }
                    %input{class:"hidden-field", type: "file", name: "main[resipi_images_attributes][4][image]", id: "main_resipi_images_attributes_4_image" }

          
          = f.text_field :main_name, class: "exhibitInput", placeholder: "主菜を入力してください"
          = f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "カテゴリーを選択してください" }, class: "exhibitInput"
          = f.collection_select :type_id, Type.all, :id, :name, { prompt: "種類を選択してください" }, class: "exhibitInput"
          .submit-area
            = f.submit :料理を登録する ,class: "exhibitSubmit1"
            = link_to "/",data: {"turbolinks" => false}, class: "exhibitSubmit2" do
              もどる

app/views/mains/search.html.haml
.wrapper
  %h1= link_to "Pochi", root_path,class: "app-title"
  .main
    .search
      .search-container
        .search-container__head
          キーワード検索
        .search-container__product-box
          .search-container__product-box__product-head
            = link_to "#", class: "line" do
              = "検索結果: #{@mains.length}件"
        .search-container__product-lists
          .week
            - @mains.each do |main|
              - if main.user_id == current_user.id
                .week__menu_show
                  %td
                    .pickup-container__product-box__product-lists__product-list
                      = link_to main_path(main), data:{"turbolinks" => false}, class: "line" do
                        - if main.first_image != nil
                          .content_post{:style => "background-image: url(#{main.first_image.image.url});"}
                        - else
                          = ""
                    .resipi_name
                      = link_to "◎#{main.main_name}◎","/mains/#{main.id}"
              - else
                = ""
  .page
    = paginate(@mains)

  .submit_area            
    = link_to "今週のこんだてを決める", "/",data: {"turbolinks" => false},class: "exhibitSubmit1"
  = render "layouts/footer"

app/views/mains/show.html.haml
= render "layouts/resipi"