config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  root "menus#index"
  resources :mains do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :subs do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :soops do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :menus do
    resources :mains, only:[:index]
    resources :subs, only:[:index]
    resources :soops, only:[:index]
    collection do
      get "menu_index"
    end
  end

  

end

app/models/soop.rb
class Soop < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :menus
  belongs_to :user
  has_many :resipi_images, dependent: :destroy
  accepts_nested_attributes_for :resipi_images, allow_destroy: true
  belongs_to_active_hash :genre
  belongs_to_active_hash :type

  validates :soop_name,              presence: true, uniqueness: { scope: :user_id}
  validates :genre_id,             presence: true
  validates :type_id,             presence: true

  def first_image
    resipi_images.first
  end

  scope :search, -> (search){where('soop_name LIKE(?)', "%#{search}%")}
end

app/controllers/soops_controller.rb
class SoopsController < ApplicationController
  before_action :set_soop,only:[:show,:destroy,:edit,:update]

  def index
    @soops = Soop.includes(:resipi_images)
  end

  def new
    if user_signed_in?
      @soop = Soop.new
      @soop.resipi_images.new
    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def create
    @soop = Soop.new(soops_params)
    if user_signed_in?
      @soop.user_id = current_user.id
      if @soop.type_id.blank? == true || @soop.genre_id.blank? == true
        redirect_to "/"
        flash[:alert] = '料理の種類かカテゴリーを選択し再度登録してください。'
      else
        if @soop.save
          redirect_to "/"
          flash[:notice] = '登録が完了しました'
        else
          @soop.resipi_images.new
          redirect_to "/"
          flash[:alert] = '料理がすでに登録されているか、空欄のため登録ができませんでした。'
        end
      end
    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def show
    if user_signed_in?
      @soop_images = @soop.resipi_images
    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def destroy
    @soop.destroy
    redirect_to root_path
    flash[:notice] = '料理が削除されました'
  end

  def edit
    if user_signed_in?
    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def update
    if @soop.update(soop_update_params)
      flash[:notice] = '料理の編集が完了しました'
      redirect_to "/soops/menu_index"
    else
      flash[:alert] = '料理の編集に失敗しました'
      redirect_to "/"
    end
  end

  def menu_index
    if user_signed_in?
      @soops = Soop.includes(:resipi_images).where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(5)
    else
      redirect_to "/"
      flash[:alert] = 'このページにアクセスするにはログインが必要です'
    end
  end

  def search
    @soops = Soop.search(params[:keyword]).where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(5)
  end

  private
  def soops_params
    params.require(:soop).permit(:id,:soop_name,:genre_id,:type_id,:comment,:user_id,resipi_images_attributes: [:image])
  end

  def soop_update_params
    params.require(:soop).permit(:id,:soop_name,:genre_id,:type_id,:comment,:user_id,[resipi_images_attributes: [:image, :_destroy, :id]])
  end

  def set_soop
    @soop = Soop.find(params[:id])
  end
end

app/helpers/soops_helper.rb
module SoopsHelper
end

app/views/soops/edit.html.haml
.wrapper
  %h1.app-title Pochi
  .exhibit
    .exhibit__resipi
      .exhibit__resipi__resipiProfile
        .exhibit__resipi__resipiProfile__inputForm
        = form_with( model: @soop, url: soop_path, local: true) do |f|
          = render 'layouts/error_messages', model: f.object
          .exhibit__resipi__resipiProfile__inputForm__resipiImage
            .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__head
                .notation 料理画像
                .formRequire 必須
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__attention
                最大5枚までアップロードできます
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__box
                - if @soop.persisted?
                  .prev-content
                    - @soop.resipi_images.each_with_index do |image, i|
                      .preview-box-soop
                        .upper-box
                          = image_tag image.image.url, data: { index: i }, width: "112", height: '112'
                        .lower-box
                          .delete-box-soop
                            %span.js-remove 削除
                  .label-content-soop
                    //プレビューの数に合わせてforオプションを指定
                    = f.label :"soop-resipi_images_attributes_#{@soop.resipi_images.length}_image", class: "label-box-soop", id: "label-box-soop--#{@soop.resipi_images.length}" do
                      %pre.label-box__text-visible クリックしてファイルをアップロード
                      .hidden-content
                        = f.fields_for :resipi_images do |i|
                          //プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置
                          .js-file_group{"data-index" => "#{i.index}"}
                            = i.file_field :image, class: "hidden-field-soop"
                          - if @soop.persisted?
                            = i.check_box:_destroy, data:{ index: i.index },class: "hidden-checkbox"
                          - if @soop.persisted?
                            .js-file_group{"data-index" => "#{@soop.resipi_images.count}"}
                          - @soop.resipi_images.length.upto(4) do |i|
                            %input{name: "soop[resipi_images_attributes][#{i}][image]", id: "soop_resipi_images_attributes_#{i}_image", class:"hidden-field-soop", type:"file"}
          = f.text_field :soop_name, class: "exhibitInput", placeholder: "副菜を入力してください"
          = f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "選択してください" }, class: "exhibitInput"
          = f.collection_select :type_id, Type.all, :id, :name, { prompt: "選択してください" }, class: "exhibitInput"
          .submit-area
            = f.submit :料理を更新する ,class: "exhibitSubmit1"
            = link_to "/",data: {"turbolinks" => false}, class: "exhibitSubmit2" do
              もどる
= render "layouts/footer"

app/views/soops/menu_index.html.haml
.wrapper
  %h1= link_to "Pochi", root_path,class: "app-title"
  
  .header__box__upper__search
    = form_with(url: search_soops_path, local: true, method: :get, class: "search-form") do |form|
      = form.text_field :keyword, placeholder: "キーワードから探す", class: "header__box__upper__search--input"
      %button{type: "submit", class: 'header__box__upper__search--btn'} 
        = icon('fas', 'search', class: 'search-icon')
  .week
    %h2.title 登録メニュー
    - @soops.each do |soop|
      - if soop.user_id == current_user.id
        .week__menu_show
          %td
            .pickup-container__product-box__product-lists__product-list
              = link_to soop_path(soop), data:{"turbolinks" => false}, class: "line" do
                - if soop.first_image != nil
                  .content_post{:style => "background-image: url(#{soop.first_image.image.url});"}
                - else
                  = ""
            .resipi_name
              = link_to "◎#{soop.soop_name}◎","/soops/#{soop.id}"
      - else
        = ""
  .page
    = paginate(@soops)

  .submit_area            
    = link_to "今週のこんだてを決める", "/",data: {"turbolinks" => false},class: "exhibitSubmit1"
= render "layouts/footer"

app/views/soops/new.html.haml
.wrapper
  %h1.app-title Pochi
  .exhibit
    .exhibit__resipi
      .exhibit__resipi__resipiProfile
        .exhibit__resipi__resipiProfile__inputForm
        = form_with( model: @soop, url: soops_path, local: true) do |f|
          = render 'layouts/error_messages', model: f.object
          .exhibit__resipi__resipiProfile__inputForm__resipiImage
            .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__head
                .notation 出品画像
                .formRequire 必須
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__attention
                最大5枚までアップロードできます
              .exhibit__resipi__resipiProfile__inputForm__resipiImage__upload__box
                .prev-content
                .label-content
                  %label{for: "soop_resipi_images_attributes_0_image", class: "label-box-soop", id: "label-box-soop--0"}
                    %pre.label-box__text-visible クリックしてファイルをアップロード
                .hidden-content
                  = f.fields_for :resipi_images do |i|
                    = i.file_field :image, class: "hidden-field"
                    %input{class:"hidden-field", type: "file", name: "soop[resipi_images_attributes][1][image]", id: "soop_resipi_images_attributes_1_image" }
                    %input{class:"hidden-field", type: "file", name: "soop[resipi_images_attributes][2][image]", id: "soop_resipi_images_attributes_2_image" }
                    %input{class:"hidden-field", type: "file", name: "soop[resipi_images_attributes][3][image]", id: "soop_resipi_images_attributes_3_image" }
                    %input{class:"hidden-field", type: "file", name: "soop[resipi_images_attributes][4][image]", id: "soop_resipi_images_attributes_4_image" }

          = f.text_field :soop_name, class: "exhibitInput", placeholder: "副菜を入力してください"
          = f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "選択してください" }, class: "exhibitInput"
          = f.collection_select :type_id, Type.all, :id, :name, { prompt: "選択してください" }, class: "exhibitInput"
          .submit-area
            = f.submit :料理を登録する ,class: "exhibitSubmit1"
            = link_to "/", data: {"turbolinks" => false},class: "exhibitSubmit2" do
              もどる

app/views/soops/search.html.haml
.wrapper
  %h1= link_to "Pochi", root_path,class: "app-title"
  .soop
    .search
      .search-container
        .search-container__head
          キーワード検索
        .search-container__product-box
          .search-container__product-box__product-head
            = link_to "#", class: "line" do
              = "検索結果: #{@soops.length}件"
        .search-container__product-lists
          .week
            - @soops.each do |soop|
              - if soop.user_id == current_user.id
                .week__menu_show
                  %td
                    .pickup-container__product-box__product-lists__product-list
                      = link_to soop_path(soop), data:{"turbolinks" => false}, class: "line" do
                        - if soop.first_image != nil
                          .content_post{:style => "background-image: url(#{soop.first_image.image.url});"}
                        - else
                          = ""
                    .resipi_name
                      = link_to "◎#{soop.soop_name}◎","/soops/#{soop.id}"
              - else
                = ""
  .page
    = paginate(@soops)

  .submit_area            
    = link_to "今週のこんだてを決める", "/",data: {"turbolinks" => false},class: "exhibitSubmit1"
  = render "layouts/footer"

app/views/soops/show.html.haml
= render "layouts/soop_resipi"