config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  root "menus#index"
  resources :mains do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :subs do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :soops do
    collection do
      get "menu_index"
    end
    collection do
      get 'search'
    end
  end
  resources :menus do
    resources :mains, only:[:index]
    resources :subs, only:[:index]
    resources :soops, only:[:index]
    collection do
      get "menu_index"
    end
  end

  

end

app/views/layouts/_error_messages.html.haml
- if @main != nil
  -if @main.errors.any?
    .alert
      %ul
        -@main.errors.full_messages.each do |message|
          %li= message
- elsif @sub != nil
  -if @sub.errors.any?
    .alert
      %ul
        -@sub.errors.full_messages.each do |message|
          %li= message
- elsif @soop != nil
  -if @soop.errors.any?
    .alert
      %ul
        -@soop.errors.full_messages.each do |message|
          %li= message

app/views/layouts/_footer.html.haml
.footer
  %ul.footer__contents
    %li.footer__contents__content
      .footer__contents__content__name
        Pochiについて
      = link_to "#", class:"kaisya" do
        会社概要
      = link_to "#", class:"privacy" do
        プライバシーポリシー
      = link_to "#", class:"kiyaku" do
        Pochi利用規約
      = link_to "#", class:"tokuyaku" do
        ポイントに関する特約
    %li.footer__contents__content
      .footer__contents__content__name
        Pochiを見る
      = link_to "#", class:"category" do
        カテゴリー一覧
      = link_to "#", class:"bland" do
        ブランド一覧
    %li.footer__contents__content
      .footer__contents__content__name
        ヘルプ&ガイド
      = link_to "#", class:"guide" do
        Pochiガイド
      = link_to "#", class:"guideline" do
        Pochiロゴ利用ガイドライン
      = link_to "#", class:"info" do
        お知らせ
  .copyright
    © Pochi

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_resipi.haml
.wrapper
  .main
    %h1= link_to "Pochi", root_path,data: {"turbolinks" => false},class: "app-title"
    .show
      .show__contents
        .show__contents__content
          .Box
            .Box__name
              %h2= "◎#{@main.main_name}◎"
            .Box__image
              %ul
                %li.top-image
                -if @main_images.blank?
                  = ""
                - else
                  = image_tag @main_images[0].image.url ,class:"mainImage"
                    - if @main.user_id.present?
                %ul
                  - @main_images.each do |image|
                    %li= image_tag image.image.url
            - if user_signed_in?
              - if @main.user_id == current_user.id
                = link_to "root_path", class:"userBtn" do
                  %h2 自分のレシピです
              - elsif @main.user_id == nil
                = link_to "root_path", class:"userBtn" do
                  %h2 フレンドが登録したレシピです
              - else
                = link_to root_path, class:"soldOutBtn" do
                  %h2 今注目のレシピです
            - else
              = link_to new_user_session_path, class:"userBtn" do
                %h2 ログインして登録
              = link_to new_user_registration_path, class:"userBtn" do
                %h2 新規会員登録して登録
            .Box__introduction
              = @main.comment
            .table
              %table.table__details
                %tr
                  %th 登録者
                  %td= @main.user.nickname
                %tr
                  %th 料理のカテゴリー
                  %td
                    = @main.genre.name 
                -if @main.type_id.present?
                  %tr
                    %th 料理の種類
                    %td= @main.type.name
                - else
                  %tr
                    %th 料理の種類
                    %td
                %tr
                  %th レシピ
                  %td.resipi-index
                    #ingredients_list
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name
                            %a.cookdict_ingredient_link{:href => "/cooking_basics/search/%E5%BC%B7%E5%8A%9B%E7%B2%89"} 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name
                            %a.cookdict_ingredient_link{:href => "/cooking_basics/search/%E3%83%8F%E3%83%81%E3%83%9F%E3%83%84"} 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 

                      

                
            .optionalArea
              %ul.optionalArea__btn
                %li.likeBtn 
                  = icon('fa', 'star')
                  お気に入り 0
              %ul.optionalArea__btn
                =link_to "#" do
                  %li.reportBtn
                    = icon('fa', 'flag')
                    不適切なレシピの通報
          - if @main.user_id != nil && current_user.id == @main.user_id
            .userSelect
              = link_to 'この料理を削除する', main_path(@main.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'user__delete'
              = link_to '料理の編集', edit_main_path(@main.id), data:{"turbolinks" => false}, class: 'user__edit'
            -# - elsif user_signed_in? && current_user.id == @main.user_id
            -#   .userSelect
            -#     = link_to '商品の編集', edit_main_path(@main.id), data:{"turbolinks" => false}, class: 'user__edit'
            -#     %p または
            -#     = link_to 'この料理を削除する', main_path(@main.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'user__delete'
          - else
            .commentBox
              .comments
                - if @comments
                  - @comments.each do |comment|
                    .comments__text__user
                      %strong
                        .comment__user
                          %p= comment.user.nickname
                        .comment__massage__text
                          = comment.text
                          %p= comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                        - if user_signed_in? && current_user.id == comment.user_id
                          .comment__delete
                            = link_to '削除', "/mains/#{@main.id}/comments/#{comment.id}", method: :delete

            .commentContents
              - if user_signed_in?
                = form_with(model: [@main], local:true, id: "new_comment") do |f|
                  = f.text_area :text, class: 'textarea', rows: "2"
                  .noticeMessage
                    相手のことを考え丁寧なコメントを心がけましょう。
                    %br
                    不快な言葉遣いなどは利用制限や退会処分となることがあります。
                  = f.submit "コメントする", class: "commentBtn"
          %ul.links
            =link_to "#" do
              %li
                = icon('fa', 'angle-left')
                %span 前の商品
            =link_to "#" do
              %li
                %span 後ろの商品
                = icon('fa', 'angle-right')
          .relateds
            

app/views/layouts/_soop_resipi.html.haml
.wrapper
  .main
    %h1= link_to "Pochi", root_path,data: {"turbolinks" => false},class: "app-title"
    .show
      .show__contents
        .show__contents__content
          .Box
            .Box__name
              %h2= "◎#{@soop.soop_name}◎"
            .Box__image
              %ul
                %li.top-image
                -if @soop_images.blank?
                  = ""
                - else
                  = image_tag @soop_images[0].image.url ,class:"mainImage"
                    - if @soop.user_id.present?
                %ul
                  - @soop_images.each do |image|
                    %li= image_tag image.image.url
            - if user_signed_in?
              - if @soop.user_id == current_user.id
                = link_to "root_path", class:"userBtn" do
                  %h2 自分のレシピです
              - elsif @soop.user_id == nil
                = link_to "root_path", class:"userBtn" do
                  %h2 フレンドが登録したレシピです
              - else
                = link_to root_path, class:"soldOutBtn" do
                  %h2 今注目のレシピです
            - else
              = link_to new_user_session_path, class:"userBtn" do
                %h2 ログインして登録
              = link_to new_user_registration_path, class:"userBtn" do
                %h2 新規会員登録して登録
            .Box__introduction
              = @soop.comment
            .table
              %table.table__details
                %tr
                  %th 登録者
                  %td= @soop.user.nickname
                %tr
                  %th 料理のカテゴリー
                  %td
                    = @soop.genre.name 
                -if @soop.type_id.present?
                  %tr
                    %th 料理の種類
                    %td= @soop.type.name
                - else
                  %tr
                    %th 料理の種類
                    %td
                %tr
                  %th レシピ
                  %td.resipi-index
                    #ingredients_list
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name
                            %a.cookdict_ingredient_link{:href => "/cooking_basics/search/%E5%BC%B7%E5%8A%9B%E7%B2%89"} 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name
                            %a.cookdict_ingredient_link{:href => "/cooking_basics/search/%E3%83%8F%E3%83%81%E3%83%9F%E3%83%84"} 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
            .optionalArea
              %ul.optionalArea__btn
                %li.likeBtn 
                  = icon('fa', 'star')
                  お気に入り 0
              %ul.optionalArea__btn
                =link_to "#" do
                  %li.reportBtn
                    = icon('fa', 'flag')
                    不適切なレシピの通報
          - if @soop.user_id != nil && current_user.id == @soop.user_id
            .userSelect
              = link_to 'この料理を削除する', soop_path(@soop.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'user__delete'
              = link_to '商品の編集', edit_soop_path(@soop.id), data:{"turbolinks" => false}, class: 'user__edit'
          - else
            .commentBox
              .comments
                - if @comments
                  - @comments.each do |comment|
                    .comments__text__user
                      %strong
                        .comment__user
                          %p= comment.user.nickname
                        .comment__massage__text
                          = comment.text
                          %p= comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                        - if user_signed_in? && current_user.id == comment.user_id
                          .comment__delete
                            = link_to '削除', "/soops/#{@soop.id}/comments/#{comment.id}", method: :delete

            .commentContents
              - if user_signed_in?
                = form_with(model: [@soop], local:true, id: "new_comment") do |f|
                  = f.text_area :text, class: 'textarea', rows: "2"
                  .noticeMessage
                    相手のことを考え丁寧なコメントを心がけましょう。
                    %br
                    不快な言葉遣いなどは利用制限や退会処分となることがあります。
                  = f.submit "コメントする", class: "commentBtn"
          %ul.links
            =link_to "#" do
              %li
                = icon('fa', 'angle-left')
                %span 前の商品
            =link_to "#" do
              %li
                %span 後ろの商品
                = icon('fa', 'angle-right')
          .relateds
            

app/views/layouts/_sub_resipi.html.haml
.wrapper
  .main
    %h1= link_to "Pochi", root_path,data: {"turbolinks" => false},class: "app-title"
    .show
      .show__contents
        .show__contents__content
          .Box
            .Box__name
              %h2= "◎#{@sub.sub_name}◎"
            .Box__image
              %ul
                %li.top-image
                -if @sub_images.blank?
                  = ""
                - else
                  = image_tag @sub_images[0].image.url ,class:"mainImage"
                    - if @sub.user_id.present?
                %ul
                  - @sub_images.each do |image|
                    %li= image_tag image.image.url
            - if user_signed_in?
              - if @sub.user_id == current_user.id
                = link_to "root_path", class:"userBtn" do
                  %h2 自分のレシピです
              - elsif @sub.user_id == nil
                = link_to "root_path", class:"userBtn" do
                  %h2 フレンドが登録したレシピです
              - else
                = link_to root_path, class:"soldOutBtn" do
                  %h2 今注目のレシピです
            - else
              = link_to new_user_session_path, class:"userBtn" do
                %h2 ログインして登録
              = link_to new_user_registration_path, class:"userBtn" do
                %h2 新規会員登録して登録
            .Box__introduction
              = @sub.comment
            .table
              %table.table__details
                %tr
                  %th 登録者
                  %td= @sub.user.nickname
                %tr
                  %th 料理のカテゴリー
                  %td
                    = @sub.genre.name 
                -if @sub.type_id.present?
                  %tr
                    %th 料理の種類
                    %td= @sub.type.name
                - else
                  %tr
                    %th 料理の種類
                    %td
                %tr
                  %th レシピ
                  %td.resipi-index
                    #ingredients_list
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name
                            %a.cookdict_ingredient_link{:href => "/cooking_basics/search/%E5%BC%B7%E5%8A%9B%E7%B2%89"} 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name
                            %a.cookdict_ingredient_link{:href => "/cooking_basics/search/%E3%83%8F%E3%83%81%E3%83%9F%E3%83%84"} 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
                      .ingredient_row
                        .ingredient_name
                          %span.name 
                        .ingredient_quantity.amount 
            .optionalArea
              %ul.optionalArea__btn
                %li.likeBtn 
                  = icon('fa', 'star')
                  お気に入り 0
              %ul.optionalArea__btn
                =link_to "#" do
                  %li.reportBtn
                    = icon('fa', 'flag')
                    不適切なレシピの通報
          - if @sub.user_id != nil && current_user.id == @sub.user_id
            .userSelect
              = link_to 'この料理を削除する', sub_path(@sub.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'user__delete'
              = link_to '商品の編集', edit_sub_path(@sub.id), data:{"turbolinks" => false}, class: 'user__edit'
          - else
            .commentBox
              .comments
                - if @comments
                  - @comments.each do |comment|
                    .comments__text__user
                      %strong
                        .comment__user
                          %p= comment.user.nickname
                        .comment__massage__text
                          = comment.text
                          %p= comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                        - if user_signed_in? && current_user.id == comment.user_id
                          .comment__delete
                            = link_to '削除', "/subs/#{@sub.id}/comments/#{comment.id}", method: :delete

            .commentContents
              - if user_signed_in?
                = form_with(model: [@sub], local:true, id: "new_comment") do |f|
                  = f.text_area :text, class: 'textarea', rows: "2"
                  .noticeMessage
                    相手のことを考え丁寧なコメントを心がけましょう。
                    %br
                    不快な言葉遣いなどは利用制限や退会処分となることがあります。
                  = f.submit "コメントする", class: "commentBtn"
          %ul.links
            =link_to "#" do
              %li
                = icon('fa', 'angle-left')
                %span 前の商品
            =link_to "#" do
              %li
                %span 後ろの商品
                = icon('fa', 'angle-right')
          .relateds
            

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", :name => "viewport"}/
    %title PochiApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{"data-turbolinks" => "false"}
    = render 'layouts/notifications'
    = yield